INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (30, 'AT&T', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (28, 'Amazon Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (29, 'Apple Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (31, 'Berkshire Hathaway', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (32, 'Boeing', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (33, 'Chevron', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (34, 'Coca-Cola Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (35, 'Comcast / NBCUniversal', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (36, 'Disney Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (37, 'ExxonMobil', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (38, 'Fox Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (39, 'Google (Alphabet)', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (40, 'IBM', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (42, 'JPMorgan Chase', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (41, 'Johnson & Johnson', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (43, 'Lockheed Martin', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (44, 'Meta Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (45, 'Microsoft Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (46, 'Oracle', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (47, 'Pfizer', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (48, 'UnitedHealth Group', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (49, 'Verizon', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (50, 'Walmart Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (543, 'Flat Earth Society', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (549, 'QAnon Hubs', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (551, 'The Great Reset Conspiracies', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (581, 'BITE Model Violators', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (582, 'Church of Scientology', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (583, 'Coercive Religious Recruitment', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (584, 'FLDS-affiliated Sites', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (585, 'Heaven''s Gate Archives', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (586, 'High-Control Group Forums', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (587, 'NXIVM-adjacent Content', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (588, 'Sovereign Citizen Networks', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (464, '4chan /pol/', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (465, 'American Renaissance', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (466, 'Daily Stormer', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (467, 'Gab', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (468, 'Parler', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (469, 'Stormfront', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (470, 'VDare', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (531, 'Antisemitic Forums', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (532, 'Incel Communities', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (533, 'Men''s Rights Extremism', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (534, 'Misogynist Content Sites', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (535, 'Nationalist Hate Sites', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (536, 'Race-Baiting Media', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (537, 'Racist Forums & Imageboards', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (538, 'White Supremacist Media', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (539, 'Xenophobic News Outlets', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (540, 'Xenophobic Social Channels', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (233, 'ABC News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (234, 'Al Jazeera', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (235, 'Associated Press', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (236, 'BBC', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (237, 'Bloomberg', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (238, 'CBS News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (239, 'CNN', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (240, 'MSN', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (241, 'NBC News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (242, 'NPR', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (243, 'Politico', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (244, 'Reuters', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (245, 'The Guardian', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (246, 'The New York Times', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (247, 'USA Today', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (248, 'Washington Post', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (249, 'ACLU', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (250, 'AllSides', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (251, 'Anti-Defamation League', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (252, 'Breitbart News', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (253, 'CAIR', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (254, 'CPAC', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (255, 'Democratic Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (256, 'Federal Election Commission', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (257, 'Government Accountability Institute', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (258, 'Green Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (259, 'Heritage Foundation', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (260, 'Libertarian Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (261, 'MoveOn.org', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (262, 'NAACP', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (263, 'NRA', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (264, 'Planned Parenthood', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (265, 'Republican Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (266, 'Southern Poverty Law Center', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (267, 'Supreme Court of the United States', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (268, 'The Drudge Report', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (269, 'Turning Point USA', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (270, 'U.S. House of Representatives', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (271, 'U.S. Senate', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (272, 'Veterans Administration', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (273, 'White House', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (633, 'Bipartisan Report', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (541, 'Brighteon', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (638, 'Crooks and Liars', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (542, 'Epoch Times', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (544, 'Gateway Pundit', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (545, 'InfoWars', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (547, 'NewsMax', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (548, 'OAN', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (631, 'Occupy Democrats', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (632, 'Palmer Report', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (550, 'Rumble (political channels)', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (636, 'Second Nexus', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (634, 'The Other 98%', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (635, 'Winning Democrats', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (637, 'Wonkette', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (552, 'ZeroHedge', 'Ragebait');
