INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (30, 'AT&T', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (28, 'Amazon Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (29, 'Apple Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (31, 'Berkshire Hathaway', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (32, 'Boeing', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (33, 'Chevron', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (34, 'Coca-Cola Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (35, 'Comcast / NBCUniversal', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (36, 'Disney Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (37, 'ExxonMobil', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (38, 'Fox Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (39, 'Google (Alphabet)', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (40, 'IBM', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (42, 'JPMorgan Chase', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (41, 'Johnson & Johnson', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (43, 'Lockheed Martin', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (44, 'Meta Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (45, 'Microsoft Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (46, 'Oracle', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (47, 'Pfizer', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (48, 'UnitedHealth Group', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (49, 'Verizon', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (50, 'Walmart Corp', 'Big Business');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (543, 'Flat Earth Society', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (549, 'QAnon Hubs', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (551, 'The Great Reset Conspiracies', 'Conspiracy & Fabricated Claims');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (581, 'BITE Model Violators', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (582, 'Church of Scientology', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (583, 'Coercive Religious Recruitment', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (584, 'FLDS-affiliated Sites', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (585, 'Heaven''s Gate Archives', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (586, 'High-Control Group Forums', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (587, 'NXIVM-adjacent Content', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (588, 'Sovereign Citizen Networks', 'Cult & Coercive Groups');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (464, '4chan /pol/', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (465, 'American Renaissance', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (466, 'Daily Stormer', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (467, 'Gab', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (468, 'Parler', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (469, 'Stormfront', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (470, 'VDare', 'Extremism & Radicalization');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (531, 'Antisemitic Forums', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (532, 'Incel Communities', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (533, 'Men''s Rights Extremism', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (534, 'Misogynist Content Sites', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (535, 'Nationalist Hate Sites', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (536, 'Race-Baiting Media', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (537, 'Racist Forums & Imageboards', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (538, 'White Supremacist Media', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (539, 'Xenophobic News Outlets', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (540, 'Xenophobic Social Channels', 'Hate & Discriminatory Content');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (233, 'ABC News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (234, 'Al Jazeera', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (235, 'Associated Press', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (236, 'BBC', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (237, 'Bloomberg', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (238, 'CBS News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (239, 'CNN', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (240, 'MSN', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (241, 'NBC News', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (242, 'NPR', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (243, 'Politico', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (244, 'Reuters', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (245, 'The Guardian', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (246, 'The New York Times', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (247, 'USA Today', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (248, 'Washington Post', 'News & Media');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (249, 'ACLU', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (250, 'AllSides', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (251, 'Anti-Defamation League', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (252, 'Breitbart News', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (253, 'CAIR', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (254, 'CPAC', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (255, 'Democratic Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (256, 'Federal Election Commission', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (257, 'Government Accountability Institute', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (258, 'Green Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (259, 'Heritage Foundation', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (260, 'Libertarian Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (261, 'MoveOn.org', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (262, 'NAACP', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (263, 'NRA', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (264, 'Planned Parenthood', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (265, 'Republican Party', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (266, 'Southern Poverty Law Center', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (267, 'Supreme Court of the United States', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (268, 'The Drudge Report', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (269, 'Turning Point USA', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (270, 'U.S. House of Representatives', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (271, 'U.S. Senate', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (272, 'Veterans Administration', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (273, 'White House', 'Politics & Government');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (633, 'Bipartisan Report', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (541, 'Brighteon', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (638, 'Crooks and Liars', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (542, 'Epoch Times', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (544, 'Gateway Pundit', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (545, 'InfoWars', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (547, 'NewsMax', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (548, 'OAN', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (631, 'Occupy Democrats', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (632, 'Palmer Report', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (550, 'Rumble (political channels)', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (636, 'Second Nexus', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (634, 'The Other 98%', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (635, 'Winning Democrats', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (637, 'Wonkette', 'Ragebait');
INSERT OR REPLACE INTO yt_items (item_id, name, category) VALUES (552, 'ZeroHedge', 'Ragebait');
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (113, 'UCXIJgqnII2ZOINSWNOGFThA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (30, 'UC0JO-FDmcF2lFP1l-rsmBWg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (30, 'UCPI6iDC1m1UXm5QKXqajKTQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (30, 'UCnpDurxReTSpFs5-AhDo8Kg', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (30, 'UCHVMnhhrpYSNNyHlo5G9eaQ', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (28, 'UCkLXELm63_pH7L-r-548kig', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (28, 'UCzE5rz2KHTFYAkmMksUpPLA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (29, 'UCE_M8A5yxnLfW0KghEeajjw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (29, 'UCYFQ33UIPERYx8-ZHucZbDA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (32, 'UC9IEkprr46ScglWU79HF5qQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UC75HjFw2U3ipbrDj3ara7bg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UCuoTMTd172R7bycLnkLOArQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UCc0yP_qyBE6Xvrdd4abE7Rg', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UCmKSfEA261itlgjkfho3tNg', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UC9XlUdBIfaCkJz4UkdoGHjA', 4);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (33, 'UCG7MOSE5VUfvaZocYhyxi4w', 5);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (34, 'UCosXctaTYxN4YPIvI5Fpcrw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (34, 'UC5JBB_E5mzPEbDupD-6fA4A', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (35, 'UCkd0_tpDvgnBqfhUzM7Q0og', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (35, 'UCccjdJEay2hpb5scz61zY6Q', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (35, 'UCl2h4q-ucsVPrIB7cFjV-fw', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (35, 'UCMxPERwMmMcJrDJM-yihUlA', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (36, 'UC_5niPa-d35gg88HaS7RrIw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (36, 'UCjTXf3A7_xnZwbgGQIdHW0Q', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (37, 'UCvNc3rg1Aa9wSPECYWEfcPg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (39, 'UCK8sQmJBp8GCxrOtXWBpyEA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (40, 'UC8cc4pVKVHG7A9fbNsRNrLQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (40, 'UCKWaEZ-_VweaEx1j62do_vQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (40, 'UCUm6InQvGI9-6vo1teGWINA', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (40, 'UCwx7Y3W30N8aS_tiCy2x-2g', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (40, 'UC9K3qy72l9D27vPeKWoUq7Q', 4);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (42, 'UCBnFes2U2diA3QfR5m8l_Tw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (42, 'UCHtxFngk49IKUfJUKXwpCQw', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (42, 'UCdzldf9mVBHWtewkFaRf5Bg', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (41, 'UCg0sL-UssDXE2Ohk3Dfpz7g', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (41, 'UCHOwWxMVtei89ur1JxMvOdA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (41, 'UC6WxClP5k-ZAaBmbY392w_w', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (43, 'UCJWcF0ex7_doPdIQGbVpDsQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (44, 'UC04FyDIvYXNecpbG8gyOw4A', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (45, 'UCFtEEv80fQVKkD4h1PF-Xqw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (46, 'UCHCThmyZ-2yWkv0UVeBDdnQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (46, 'UCdDhYMT2USoLdh4SZIsu_1g', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (46, 'UC60OcDzeEtn194-UPYNJs8A', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (47, 'UCzoP7l5bzSzi2gUUNn0I79w', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (47, 'UCL7KWa15C0d198RewsBQiEA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (47, 'UCEkMv1toEgnBqLlkru6dNtQ', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (47, 'UCHYITGP-kzfpkbvHz6BTjEQ', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (48, 'UCET63-QbBE2_l435xQaPgrw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (48, 'UCA9mvhiRY3VT95NPrpo1BWQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (49, 'UCDF1rHyRH8LcxbHX5_mrZ0w', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (49, 'UCL9bd7Pw6c_HXXusLswHGYw', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (49, 'UC7Bly_C-0LazNgMyD-qVy9g', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (49, 'UC04snGzW8SWUeoMXPl43uyQ', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (50, 'UC701pqb1-HJPS4RMjSmK4Yg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (50, 'UCT5JDZ41sV-gaPF5gnRLThA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (543, 'UCNMB7svMVQZeQ6_GV-0PwCQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCTODir8fjkXwRvbTC6_DQjw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCHShroyV2IVhDoNW0O2x90Q', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCXyj8Cyw4zfs75yiU_w1i4A', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCEzWJit48bIMFCEG0JJ36eA', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCH5fLGK91befD3nAWAM9zxw', 4);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (582, 'UCEdzK6VibI80vlYWnd9tfUQ', 5);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (585, 'UC0ImLBqX904QWHFzDqLza-A', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (585, 'UCFviL9N0H0CCTl3ql-b1kzw', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (585, 'UCAuYZDJmwojYBN0gjRLr5_w', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (587, 'UCMWvfA27XqQFsqQXAFIJnmQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (465, 'UCMLbmp5tcLxzahMLTmeM4lg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (466, 'UCD7NcsKmJwXTe_L-J9UpqSg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (468, 'UC49fOhnFP0R3AJYfzj2PdsQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (233, 'UCBi2mrWuNuyYy4gbM6fU18Q', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (234, 'UCNye-wNBqNL5ZzHSJj3l8Bg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (234, 'UCfiwzLy-8yKzIbsmZTzxDgw', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (235, 'UC52X5wxOL_s5yw0dQk7NtgA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (236, 'UC16niRr50-MSBwiO3YDb3RA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (236, 'UCCj956IF62FbT7Gouszaj9w', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (237, 'UCIALMKvObZNtJ6AmdCLP7Lg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (237, 'UCUMZ7gohGI9HcU9VNsr2FJQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (237, 'UChirEOpgFCupRAk5etXqPaA', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (237, 'UC7UFcUbAd8oyCBWCogVpJ6g', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (237, 'UChF5O40UBqAc82I7-i5ig6A', 4);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (238, 'UC8p1vwvWtl6T73JiExfWs1g', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (239, 'UCupvZG-5ko_eiXAupbDfxWw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (240, 'UC0JKJQrPifOha3KqSU4IpOg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (241, 'UCeY0bbntWzzVIaj2z3QigXg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (242, 'UCJnS2EsPfv46u1JR8cnD0NA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (243, 'UCgjtvMmHXbutALaw9XzRkAg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (244, 'UChqUTb7kYRX8-EiaN3XFrSQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCHpw8xwDNhU9gdohEcJu4aA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCIRYBXDze5krPDzAEOxFGVA', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UC4OxS-w63-g00lI7nGkzpcw', 2);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCwD9E_QNwFwrQC7OnPnrg2Q', 3);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCNHqb1IRxQ5WBsWtO53JL2g', 4);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCUnMSn34D2TxKnEJQ9VYWkQ', 5);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCoWKwd06OC0Y0XpvAa8jfdw', 6);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (245, 'UCVD6kK-I5NodC1s-JMeuYPw', 7);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (246, 'UCqnbDFdCpuN8CMEg0VuEBqA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (247, 'UCP6HGa63sBC7-KHtkme-p-g', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (247, 'UCa_U2HRBQrWRBVUt6iOBjzQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (248, 'UCHd62-u_v4DvJ8TCFtpi4GA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (248, 'UCt_SXDdK6qBv4FfJ8DybxKg', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (249, 'UC7M42vQrNmZ0tnmmenLWwBA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (250, 'UCG9TfKVhTQwBZbJJMwnkJLg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (251, 'UCfVotMGyD7sVMomr2AzsBtQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (253, 'UCFYW2x6hlPQsAjhzfX5F6ug', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (254, 'UCVlD5RMKD1bv-JiAT7KVX5Q', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (255, 'UClkO4MArT2WKWj32YDD_-Ew', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (256, 'UCpyA3jv66mB8he1lS2z4ZQw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (257, 'UC_xyXt1a0-hTLoZUoYr4YMg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (258, 'UCZfnQZquRwx_F6yZg3g9kOw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (259, 'UC5bEfSFTYQVfLCwkhBt8NtQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (260, 'UCcCicSfSLjc8AD46Zvo_zYA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (261, 'UCExmL8PAa1O93bUIYN7BJ_A', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (262, 'UCjIwnDSmohltS_z8YCuZUHg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (263, 'UCZr49eSL2aHQ_41476IrkbA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (264, 'UCkNJfjuNyIopt8UyC5ofhwg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (265, 'UC3o7kbpTUQ5-0WTMIp8sVwA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (266, 'UCJqloayL-p1TP4Ed_fr53CA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (269, 'UCVrK_pMRp_q8IelpfUCTGLQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (271, 'UCBFW8zxJyf-EpTGU9sEjd0w', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (272, 'UCBvOzPLmbzjtpX-Htstp2vw', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (273, 'UCYxRlFDqcWM4y7FfpiAN3KQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (633, 'UClfK5oFd4VqpTtCblkFoYtA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (638, 'UCzTy5FV9S-JqMaJOq4AxySQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (542, 'UCeLc4heXqG9dtL7jiPHMBfQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (544, 'UCMaLetBcZ8fqsoIryB015og', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (547, 'UCx6h-dWzJ5NpAlja1YsApdg', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (548, 'UCNbIDJNNgaRrXOD7VllIMRQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (548, 'UCfsibRlgwY9_7ypPJc5OzTw', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (631, 'UCn_uMY15GlwaPpx80-WjR6g', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (634, 'UCi_vSLFeG_O6NOOWhkGMDnQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (637, 'UCUlXFewpX6ZProHdsAfsknQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (552, 'UCaO9gH0HOmvXjZg_tMG0lLQ', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (252, 'UCmgnsaQIK1IR808Ebde-ssA', 0);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (252, 'UCDOIXHGP4D7GMtYvnZ0ldwQ', 1);
INSERT OR IGNORE INTO yt_channels (item_id, channel_id, sort_order) VALUES (252, 'UCZz3-vgIPzgvYBS60_BSPuw', 2);
