#!/usr/bin/env python3
"""Stamp the shared header nav (and a footer where none exists) onto every
top-level page except index.html, which owns the styled original.

Idempotent: blocks live between HAVEN-SHARED-NAV / HAVEN-SHARED-FOOTER markers
and are replaced wholesale on each run. Called from data/sql/build.py so the
menu can never drift between pages again (Dave's ruling, 2026-08-17:
Demo - Benefits - Features - Milestones - About us on every page).
"""
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent

NAV = """<!-- HAVEN-SHARED-NAV START (generated by tools/inject-nav.py; edit there) -->
<style>
.hvn-shared-nav { background:#171b20; border-bottom:2px solid #c40000; font-family:system-ui,sans-serif; }
.hvn-shared-nav .inner { max-width:1080px; margin:0 auto; padding:10px 18px; display:flex; align-items:center; gap:18px; flex-wrap:wrap; }
.hvn-shared-nav a { color:#e8edf2; text-decoration:none; font-size:15px; }
.hvn-shared-nav a:hover { color:#ff6a6a; }
.hvn-shared-nav .brand { font-weight:700; font-size:17px; color:#fff; margin-right:8px; }
</style>
<div class="hvn-shared-nav"><div class="inner">
  <a class="brand" href="index.html">Haven</a>
  <a href="demo.html">Demo</a>
  <a href="benefits.html">Benefits</a>
  <a href="features.html">Features</a>
  <a href="milestones.html">Milestones</a>
  <a href="screen-haven.html">Screen Haven</a>
  <a href="about.html">About us</a>
</div></div>
<!-- HAVEN-SHARED-NAV END -->"""

FOOTER = """<!-- HAVEN-SHARED-FOOTER START (generated by tools/inject-nav.py; edit there) -->
<style>
.hvn-shared-footer { background:#171b20; border-top:1px solid #333; margin-top:48px; font-family:system-ui,sans-serif; }
.hvn-shared-footer .inner { max-width:1080px; margin:0 auto; padding:18px; text-align:center; }
.hvn-shared-footer a { color:#aab4be; text-decoration:none; font-size:14px; margin:0 10px; }
.hvn-shared-footer a:hover { color:#ff6a6a; }
.hvn-shared-footer .copy { color:#667; font-size:12px; margin-top:10px; }
</style>
<div class="hvn-shared-footer"><div class="inner">
  <a href="benefits.html">Benefits</a><a href="features.html">Features</a><a href="demo.html">Demo</a><a href="milestones.html">Milestones</a><a href="screen-haven.html">Screen Haven</a><a href="faq.html">FAQ</a><a href="about.html">About us</a><a href="fun.html">Fun and games!</a>
  <p class="copy">&copy; Copyright 2026 Lulhaven &mdash; All Rights Reserved</p>
</div></div>
<!-- HAVEN-SHARED-FOOTER END -->"""

NAV_RE = re.compile(r"<!-- HAVEN-SHARED-NAV START.*?HAVEN-SHARED-NAV END -->", re.S)
FOOT_RE = re.compile(r"<!-- HAVEN-SHARED-FOOTER START.*?HAVEN-SHARED-FOOTER END -->", re.S)
BODY_RE = re.compile(r"(<body[^>]*>)", re.I)

def stamp(path: Path) -> str:
    html = path.read_text(encoding="utf-8")
    orig = html
    if NAV_RE.search(html):
        html = NAV_RE.sub(NAV, html)
    else:
        m = BODY_RE.search(html)
        if not m:
            return "no <body>"
        html = html[:m.end()] + "\n" + NAV + html[m.end():]
    if FOOT_RE.search(html):
        html = FOOT_RE.sub(FOOTER, html)
    elif "<footer" not in html:
        idx = html.lower().rfind("</body>")
        if idx != -1:
            html = html[:idx] + FOOTER + "\n" + html[idx:]
    if html != orig:
        path.write_text(html, encoding="utf-8")
        return "stamped"
    return "unchanged"

def main():
    results = []
    for page in sorted(SITE.glob("*.html")):
        if page.name == "index.html":
            continue
        results.append((page.name, stamp(page)))
    for name, r in results:
        print(f"{r:9s}  {name}")
    bad = [n for n, r in results if r == "no <body>"]
    return 1 if bad else 0

if __name__ == "__main__":
    sys.exit(main())
